Feat(default components): add default component、standard css
masastack/MASA.Stack.Components pull request #21
Opened 2022-05-31 05:38 UTC by 15168440402

2022-05-31 06:23 UTC, capdiem requested changes

2022-05-31 06:23 UTC, capdiem commented on src/Masa.Stack.Components/IntegrationComponents/Defaults/DefaultIcon.cs
> +public class DefaultIcon : MIcon
这个组件没意义。

2022-05-31 06:23 UTC, capdiem commented on src/Masa.Stack.Components/IntegrationComponents/Defaults/DefaultPagination.razor
> +﻿@namespace Masa.Stack.Components
这个组件不属于Default，改个名字即可。

2022-05-31 06:23 UTC, capdiem commented on src/Masa.Stack.Components/IntegrationComponents/Upload/Upload.razor.cs
> +    IJSObjectReference? UploadJs { get; set; }
需要在Dispose中释放掉。

2022-05-31 06:23 UTC, capdiem commented on src/Masa.Stack.Components/IntegrationComponents/Upload/UploadImage.razor.cs
> +    {
默认参数值放在SetParametersAsync base之前。

2022-05-31 06:57 UTC, capdiem requested changes

2022-05-31 06:57 UTC, capdiem commented on src/Masa.Stack.Components/IntegrationComponents/Defaults/DefaultDataTable.cs
> +        Class ??= "";
Class写在OnParametersSet()里，另外在class前加个空格 " table-border-none"

2022-05-31 10:04 UTC, capdiem approved these changes
LGTM.

2022-05-31 10:05 UTC, capdiem commented
@doddgu

2022-06-01 02:56 UTC, doddgu approved these changes
LGTM

2022-06-01 02:56 UTC, merged