feat(component):add PaginationSelect Component、reduction ui
masastack/MASA.Stack.Components pull request #33
Opened 2022-06-21 09:44 UTC by wuweilai

2022-06-22 05:56 UTC, capdiem requested changes

2022-06-22 05:56 UTC, capdiem commented on src/Masa.Stack.Components/IntegrationComponents/PaginationSelect.razor.cs
> +    private string Icon { get; set; } = "mdi-menu-down";
Menu用`@bind-Value`，然后 Icon => menuValue ? "mdi-menu-down": "mdi-menu-up"不好吗？

2022-06-22 05:56 UTC, capdiem commented on src/Masa.Stack.Components/IntegrationComponents/PaginationSelect.razor.cs
> +        Value = value;
把`Value=value`放在`else`里去，不然会存在一些问题，具体原因我忘记了我记得遇到坑。至少改动后Value的Set只会执行一次。

2022-06-23 05:20 UTC, capdiem approved these changes
LGTM @doddgu

2022-06-23 06:54 UTC, doddgu approved these changes
LGTM

2022-06-23 06:54 UTC, merged