feat(layout):update layout data from auth
masastack/MASA.Stack.Components pull request #34
Opened 2022-06-22 01:48 UTC by MayueCif

2022-06-22 06:21 UTC, capdiem requested changes

2022-06-22 06:21 UTC, capdiem commented on src/Masa.Stack.Components/Masa.Stack.Components.csproj
>      <PackageReference Include="Masa.Blazor" Version="0.5.0-preview.2" />
升级到 preview.3

2022-06-22 06:21 UTC, capdiem commented on src/Masa.Stack.Components/Layouts/Layout.razor
> +@inject IAuthClient authClient
authClient开头大写

2022-06-22 06:21 UTC, capdiem commented on src/Masa.Stack.Components/Layouts/Layout.razor
> +        <GlobalNavigation OnFavoriteAdd="async (code)=>{await authClient.PermissionService.AddFavoriteMenuAsync(Guid.Parse(code));}"
用个方法接吧。

2022-06-22 06:21 UTC, capdiem commented on src/Masa.Stack.Components/GlobalNavigations/GlobalNavigation.razor
> +@inject IAuthClient authClient
authClient开头大写

2022-06-22 06:39 UTC, capdiem approved these changes
LGTM.

2022-06-23 01:49 UTC, doddgu approved these changes
LGTM

2022-06-23 01:49 UTC, merged