reqair SSheetDialog onclose stopPropagation
masastack/MASA.Stack.Components pull request #346
Opened 2023-02-23 07:29 UTC by zyz

# Description

_Please explain the changes you've made_

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

2023-02-23 10:59 UTC, doddgu requested changes

2023-02-23 10:59 UTC, doddgu commented on src/Masa.Stack.Components/Shared/IntegrationComponents/SSheetDialog.razor
> +            Console.WriteLine("SSheetDialog HasDelegate OnClose");
Remove the debug info.

2023-02-23 10:59 UTC, doddgu commented on src/Masa.Stack.Components/Shared/IntegrationComponents/SSheetDialog.razor
> +            Console.WriteLine("SSheetDialog OnClose");
Remove the debug info.

2023-02-23 11:00 UTC, doddgu commented
@capdiem PTAL

2023-02-28 08:41 UTC, capdiem requested changes

2023-02-28 08:41 UTC, capdiem commented on src/Masa.Stack.Components/Shared/IntegrationComponents/SSheetDialog.razor
> +        <div @attributes="context.Attrs" style="@($"padding-right:{Padding}px;padding-left:{Padding}px")" class="m-sheet-dialog-overlay d-flex flex-column full-height" @onclick="OnClose" stopPropagat
`@onclick:stopPropgation`

2023-02-28 08:41 UTC, capdiem commented on src/Masa.Stack.Components/Shared/IntegrationComponents/SSheetDialog.razor
> +                <div @onclick="OnClose" stopPropagation class="m-sheet-dialog-header d-flex align-center justify-space-between px-3" style="@($"height:{HeaderHeight}px;")">
`@onclick:stopPropgation`

2023-02-28 09:57 UTC, zyz commented
1.Remove the debug info.
2.stopPropgation to @onclick:stopPropgation
[resolved]

2023-02-28 12:57 UTC, doddgu approved these changes

2023-02-28 13:03 UTC, capdiem approved these changes

2023-02-28 13:04 UTC, merged