Fix the problem of SSheetDialog closing rendering and provide OnClose…
masastack/MASA.Stack.Components pull request #395
Opened 2023-03-13 09:48 UTC by kogel-net

…d event

# Description

_Please explain the changes you've made_

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

2023-03-13 11:52 UTC, doddgu commented
@MayueCif PTAL

2023-03-14 02:18 UTC, capdiem requested changes

2023-03-14 02:18 UTC, capdiem commented on src/Masa.Stack.Components/Shared/IntegrationComponents/SSheetDialog.razor
> +        }
```suggestion
        if (OnClosed.HasDelegate)
        {
            NextTick(async () =>
            {
                await Task.Delay(150);
                await OnClosed.InvokeAsync(Ref);
            });
        }
```

2023-03-14 02:18 UTC, capdiem commented on src/Masa.Stack.Components/Shared/IntegrationComponents/SSheetDialog.razor
> +    public EventCallback<ElementReference> OnClosed { get; set; }
```suggestion
    public EventCallback OnClosed { get; set; }
```

2023-03-14 02:25 UTC, capdiem requested changes

2023-03-14 02:25 UTC, capdiem commented on src/Masa.Stack.Components/Shared/IntegrationComponents/SSheetDialog.razor
> +@inherits BDomComponentBase
```suggestion
@inherits NextTickComponentBase
```

2023-03-14 02:29 UTC, capdiem approved these changes
LGTM

2023-03-14 02:30 UTC, merged