Feature:add auth componment and simple
masastack/MASA.Stack.Components pull request #5
Opened 2022-04-11 09:54 UTC by MayueCif

2022-04-18 15:56 UTC, capdiem requested changes

2022-04-18 15:56 UTC, capdiem commented on src/Masa.Stack.Components/SheetDialog/SheetDialog.razor.css
> +/*
这些注释可以删掉吗？

2022-04-18 15:56 UTC, capdiem commented on src/Masa.Stack.Components/ClickedExtend/ClickedExtend.razor
> +﻿@namespace Masa.Stack.Components
1. 组件名完全没有体现组件的用处。SearchableTitle？
2. 没有动画
3. 默认Title时的高度和搜索时的高度可以做成一致的。

2022-04-18 15:56 UTC, capdiem commented on src/Masa.Stack.Components/ClickedExtend/ClickedExtend.razor
> +        <MCard Style="@(IsExpanded ? displayFlex : displayNone)" class="m-click-extend-item">
不如用`bool cardStyle => IsExpanded ? "...flex" : "...none"`

2022-04-18 15:56 UTC, capdiem commented on src/Masa.Stack.Components/ClickedExtend/ClickedExtend.razor.cs
> +    public bool IsExpanded { get; set; }
乱入 [Parameter]s？

2022-04-18 15:56 UTC, capdiem commented on src/Masa.Stack.Components/ClickedExtend/ClickedExtend.razor.cs
> +    protected override void OnParametersSet()
Remove~~

2022-04-18 15:56 UTC, capdiem commented on src/Masa.Stack.Components/ClickedExtend/ClickedExtend.razor.cs
> +    public EventCallback<KeyboardEventArgs> OnKeyDown { get; set; }
不如直接暴露 `OnEnter`

2022-04-18 15:56 UTC, capdiem commented on src/Masa.Stack.Components/ClickedExtend/ClickedExtend.razor.cs
> +    public RenderFragment? ExtendContent { get; set; }
有必要提供ExtendContent吗，不就只有一个输入框吗。自定义ExtendContent后，OnKeyDown和OnBlur就没用了吧。

2022-04-18 15:56 UTC, capdiem commented on src/Masa.Stack.Components/DataTableFooter/SimpleDataTableFooter.razor.cs
> +    public string TotalStringFormat { get; set; } = "总计：{0}";
`Func<long, string>`

2022-04-18 15:56 UTC, capdiem commented on src/Masa.Stack.Components/DataTableFooter/SimpleDataTableFooter.razor.cs
> +    public EventCallback OnPrevious { get; set; }
OnPrev

2022-04-18 15:56 UTC, capdiem commented on src/Masa.Stack.Components/DataTableFooter/SimpleDataTableFooter.razor.cs
> +    protected override void OnParametersSet()
Remove~~

2022-04-18 15:56 UTC, capdiem commented on src/Masa.Stack.Components/DataTableFooter/SimpleDataTableFooter.razor.cs
> +    public EventCallback<int> OnSelectedPageSize { get; set; }
OnPageSzieChanged

2022-04-18 15:56 UTC, capdiem commented on src/Masa.Stack.Components/DataTableFooter/SimpleDataTableFooter.razor.cs
> +    public string PreIcon { get; set; } = "mdi-chevron-left";
PrevIcon

2022-04-18 15:56 UTC, capdiem commented on src/Masa.Stack.Components/DataTableFooter/SimpleDataTableFooter.razor.cs
> +    public bool TotalShow { get; set; }
Total默认应该现实吧。然后TotalShow改为HideTotal.

2022-04-18 15:56 UTC, capdiem commented on src/Masa.Stack.Components/DataTableFooter/SimpleDataTableFooter.razor.cs
> +public partial class SimpleDataTableFooter
为什么要加`Simple`呢？

2022-04-18 15:56 UTC, capdiem commented on src/Masa.Stack.Components/DataTableFooter/SimpleDataTableFooter.razor
> +        <span class="mx-4">@((Page-1)*PageSize+1) - @(Page*PageSize) of @Total</span>
暴露个参数出去怎么样？`Func<(int a, int b, long total), string>`

2022-04-18 15:56 UTC, capdiem commented on src/Masa.Stack.Components/MiniComponents/ColorGroup.razor
> +            <MCard Class="elevation-0" Style="@($"transition: opacity .4s ease-in-out; {(context.Active ? "" : "opacity: 0.5;")}")">
Card的背景颜色默认是白色，需要处理下。

2022-04-18 15:56 UTC, capdiem commented on src/Masa.Stack.Components/MiniComponents/ColorGroup.razor
> +                <MButton StopPropagation Fab class="mx-1 rounded-circle" OnClick="()=>{ context.Toggle(); ValueChanged.InvokeAsync(color); }"
OnClick用个方法接.

2022-04-18 15:56 UTC, capdiem commented on src/Masa.Stack.Components/MiniComponents/ColorGroup.razor.cs
> +    public List<string> Colors { get; set; } = new();
如果用户传了个`null`的话会报错，需要在OnParametersSet里确认不会为`null`。

2022-04-18 15:56 UTC, capdiem commented on src/Masa.Stack.Components/MiniComponents/GroupBox.razor
> +﻿@namespace Masa.Stack.Components
不理解这个组件。

2022-04-18 15:56 UTC, capdiem commented on src/Masa.Stack.Components/SheetDialog/SheetDialog.razor
> +    private async Task OnClose() => await ValueChanged.InvokeAsync(false);
在没有使用双向绑定的情况下无法关闭吧？

2022-04-18 15:56 UTC, capdiem commented on src/Masa.Stack.Components/DataTableFooter/SimpleDataTableFooter.razor
> +        <MIcon Size="24" OnClick="OnPrevious">@PreIcon</MIcon>
为啥不用`MButton Icon`

2022-04-19 09:06 UTC, capdiem approved these changes
LGTM.

2022-04-19 10:07 UTC, doddgu requested changes
LGTM

2022-04-19 10:07 UTC, doddgu commented on src/Masa.Stack.Components/SearchableExtend/SearchableExtend.razor.cs
> +    string cardStyle => IsExpanded ? displayFlex : displayNone;
=> is property, `cardStyle` must be Pascal

2022-04-19 10:07 UTC, doddgu commented on src/Masa.Stack.Components/SheetDialog/SheetDialog.razor
> +    public string IconColor { get; set; } = "#05CD99";
Why not get color from theme

2022-04-19 10:41 UTC, doddgu approved these changes
LGTM

2022-04-19 10:43 UTC, merged